### ISSUE TITLE
Possible wrong sign in OHud

### ISSUE THREAD

**Issue by MJKirk** [SMEFTsim/SMEFTsim#3]
I think the sign of the operator O_Hud might be wrong - I noticed this since I think that it should contribute to the W-u-d vertex with the same sign as the O_Hq^(3) operator, and currently SMEFTsim shows them having opposite signs.

Looking at the FeynRules source, and comparing
https://github.com/SMEFTsim/SMEFTsim/blob/db7d4a80bdcff424eee27dde71f1eb09ac894039/FeynRules_source/SMEFTsim_operators.fr#L207-L210
which should be (roughly, just thinking about SU(2) indices) Htilde^dagger D_\mu H,
with the Yukawa term for the up quarks
https://github.com/SMEFTsim/SMEFTsim/blob/db7d4a80bdcff424eee27dde71f1eb09ac894039/FeynRules_source/SMEFTsim_main.fr#L369
which is Htilde^dagger q,
it looks to me like the epsilon indices are the wrong way around in the OHud definition (or the `ii` and `jj` in the two `Phi`s should be swapped)

(Actually, I guess also shouldn't `OHud` have one `Phibar` and one `Phi`? Although it doesn't make a difference since we are using unitary gauge)

**Comment by IlariaBrivio** [comment]
Hi Matthew,
I've just had a look and I think you are right: there is an overall sign difference between the definition in the manual and what is actually in the code. I'll fix that. Thanks for noticing!

Re Phibar and Phi: you actually need two non-conjugated doublets to make the hypercharges cancel. It's 1/2 + 1/2 - 2/3 -1/3=0.
that's why it's (phi tilde)^+  in the definition and not just Phi^+.

**Comment by MJKirk** [comment]
Great - thanks for the speedy check!
Oh yes, I forgot that Htilde includes a complex conjugation, so Htilde^dagger is ~Phi not Phibar - too busy thinking about epsilon part.
